/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.penjualan.desktop.InternalFrame;

import aplikasi.penjualan.desktop.util.NavigatorForm;
import com.sunday.june.aplikasi.penjualan.controller.BarangController;
import com.sunday.june.aplikasi.penjualan.controller.FakturController;
import com.sunday.june.aplikasi.penjualan.controller.KwitansiController;
import com.sunday.june.aplikasi.penjualan.controller.PelangganController;
import com.sunday.june.aplikasi.penjualan.orm.Faktur;
import com.sunday.june.aplikasi.penjualan.orm.Fakturdetail;
import com.sunday.june.aplikasi.penjualan.orm.Kwitansi;
import com.sunday.june.aplikasi.penjualan.orm.Pelanggan;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Null Pointer
 */
public class FormKwitansi extends javax.swing.JInternalFrame implements NavigatorForm {
private DefaultTableModel tblModel;
private DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
private DecimalFormat decimalFormat = new DecimalFormat("Rp #,###");
private Faktur faktur = new Faktur();
private FakturController fkCtrl = new FakturController(aplikasi.penjualan.desktop.AplikasiPenjualanDesktop.emf);
private Kwitansi kwitansi = new Kwitansi();
private KwitansiController kwCtrl = new KwitansiController(aplikasi.penjualan.desktop.AplikasiPenjualanDesktop.emf);
private Pelanggan pelanggan = new Pelanggan();
private PelangganController plgCtrl = new PelangganController(aplikasi.penjualan.desktop.AplikasiPenjualanDesktop.emf);
private BarangController brgController = new BarangController(aplikasi.penjualan.desktop.AplikasiPenjualanDesktop.emf);
    /**
     * Creates new form FormKwitansi
     */
    public FormKwitansi() {
        initComponents();
        inisialisaiComponen();
        jtxtTanggalKwitansi.setText(dateFormat.format(new Date()));
        clearTable();
        jtxtNomorKwitansi.setText(kwCtrl.createNomorKwitansi());
    }
    
    private void inisialisaiComponen(){
             tblModel = new DefaultTableModel(){
          Class[] types = new Class[]{
            java.lang.Integer.class,
            java.lang.String.class,
            java.lang.String.class,
            java.lang.Double.class,
            java.lang.Integer.class,
            java.lang.Double.class,
          }; 
          boolean[] canEdit = new boolean[]{
              false,
              false,
              false,
              false,
              false,
              false
          };

            @Override
            public Class<Class> getColumnClass(int i) {
            return types[i];
            }

            @Override
            public boolean isCellEditable(int i, int i1) {
            return canEdit[i1];
            }
          
        };
        tblModel.addColumn("NO");
        tblModel.addColumn("Kode Barang");
        tblModel.addColumn("Nama Barang");
        tblModel.addColumn("Harga Barang");
        tblModel.addColumn("Qty");
        tblModel.addColumn("Total");
        jTable1.setModel(tblModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNomorKwitansi = new javax.swing.JTextField();
        jtxtNomorFaktur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtTanggalKwitansi = new javax.swing.JFormattedTextField();
        jtxtTanggalFaktur = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtKodePelanggan = new javax.swing.JTextField();
        jtxtNamaPelanggan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtGrandTotal = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Form Kwitansi");

        jLabel1.setText("Nomor Kwitansi ");

        jLabel2.setText("Nomor Faktur");

        jtxtNomorKwitansi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNomorKwitansiKeyPressed(evt);
            }
        });

        jtxtNomorFaktur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtNomorFakturKeyPressed(evt);
            }
        });

        jLabel3.setText("Tanggal Kwitansi");

        jLabel4.setText("Tanggal Faktur");

        jtxtTanggalKwitansi.setEditable(false);
        jtxtTanggalKwitansi.setFocusable(false);

        jtxtTanggalFaktur.setEditable(false);
        jtxtTanggalFaktur.setFocusable(false);

        jLabel5.setText("Kode Pelanggan");

        jtxtKodePelanggan.setEditable(false);
        jtxtKodePelanggan.setFocusable(false);

        jtxtNamaPelanggan.setEditable(false);
        jtxtNamaPelanggan.setFocusable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtNomorKwitansi)
                                    .addComponent(jtxtNomorFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtKodePelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtTanggalKwitansi)
                                    .addComponent(jtxtTanggalFaktur, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jtxtNamaPelanggan)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNomorKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtTanggalKwitansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxtNomorFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jtxtTanggalFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxtKodePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNomorFakturKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomorFakturKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jtxtNomorKwitansi.setText("");
            jtxtTanggalKwitansi.setText(dateFormat.format(new Date()));
            checkDataFaktur();
            
        }
    }//GEN-LAST:event_jtxtNomorFakturKeyPressed

    private void jtxtNomorKwitansiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomorKwitansiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            cariData();
        }
    }//GEN-LAST:event_jtxtNomorKwitansiKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtGrandTotal;
    private javax.swing.JTextField jtxtKodePelanggan;
    private javax.swing.JTextField jtxtNamaPelanggan;
    private javax.swing.JTextField jtxtNomorFaktur;
    private javax.swing.JTextField jtxtNomorKwitansi;
    private javax.swing.JFormattedTextField jtxtTanggalFaktur;
    private javax.swing.JFormattedTextField jtxtTanggalKwitansi;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clearData() {
    jtxtNomorKwitansi.setText("");
    jtxtNomorFaktur.setText("");
    jtxtTanggalFaktur.setText("");
    jtxtKodePelanggan.setText("");
    jtxtNamaPelanggan.setText("");
    clearTable();
    }

    @Override
    public void newData() {
    clearData();
    jtxtTanggalKwitansi.setText(dateFormat.format(new Date()));
    jtxtNomorKwitansi.setText(kwCtrl.createNomorKwitansi());
    
    
    }

    @Override
    public void saveData() {
    Faktur fk = fkCtrl.cari(jtxtNomorFaktur.getText());
    if(fk == null){
        JOptionPane.showMessageDialog(this, "Nomor Faktur Tidak ada !!!");
    }else{
        faktur = fk;
        Kwitansi kw = kwCtrl.cari(jtxtNomorKwitansi.getText());
        if(kw==null){
            kwitansi = new Kwitansi();
            kwitansi.setNomorkwitansi(kwCtrl.createNomorKwitansi());
            setData();
            try {
                kwCtrl.simpan(kwitansi);
                JOptionPane.showMessageDialog(this, "Kwitansi Berhasil Disimpan!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Kwitansi Gagal Di Simpan : "+ e.getMessage());
            }
        }else{
            kwitansi = kw;
            setData();
            try {
                kwCtrl.edit(kwitansi);
                JOptionPane.showMessageDialog(this, "Kwitansi Berhasil Disimpan!!!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Kwitansi gagal disimpan : "+ e.getMessage());
            }
        }
        
       showData();
    }
    
    }

    @Override
    public void setData() {
        try {
            kwitansi.setTanggalkwitansi(dateFormat.parse(jtxtTanggalKwitansi.getText()));
        } catch (ParseException e) {
        }
    kwitansi.setNomorfaktur(faktur);
    }

    @Override
    public void deleteData() {
        try {
            kwCtrl.hapus(jtxtNomorKwitansi.getText());
            JOptionPane.showMessageDialog(this, "Kwitansi Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kwitansi Gagal Dihapus : "+e.getMessage());
        }
    }

    @Override
    public void cariData() {
    Kwitansi k = kwCtrl.cari(jtxtNomorKwitansi.getText());
    if(k==null){
        newData();
    }else{
        kwitansi = k;
        showData();
    }
    
    }

    @Override
    public void showData() {
    
    if(kwitansi==null){
        newData();
    }else{
        jtxtNomorKwitansi.setText(kwitansi.getNomorkwitansi());
        jtxtTanggalKwitansi.setText(dateFormat.format(kwitansi.getTanggalkwitansi()));
        jtxtNomorFaktur.setText(kwitansi.getNomorfaktur().getNomorfaktur().toString());
        cariDataFaktur();
    }
    }

    @Override
    public void printData() {
        EntityManager em = null;
        try {
            em = aplikasi.penjualan.desktop.AplikasiPenjualanDesktop.emf.createEntityManager();
            em.getTransaction().begin();
            Connection con = em.unwrap(Connection.class);
            File file = new File("");
            String sourceFile = file.getAbsolutePath()+"//report//Kwitansi.jasper";
            HashMap param = new HashMap();
            param.put("nomorkwitansi", jtxtNomorKwitansi.getText());
            JasperPrint jPrint = JasperFillManager.fillReport(sourceFile, param, con);
            JasperViewer jView = new JasperViewer(jPrint, false);
            jView.setFitWidthZoomRatio();
            jView.setVisible(true);
            em.getTransaction().commit();
            
            con.close();
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kwitansi Tidak Bisa Print"+e.getMessage());
        }finally{
            if(em != null){
                em.close();
            }
        }
        
        
        
    }
    private void clearTable(){
        int row = tblModel.getRowCount();
        while(row>0){
            row--;
            tblModel.removeRow(row);
        }
    }
    private void showDataFaktur(){
        if(faktur!=null){
            jtxtNomorFaktur.setText(faktur.getNomorfaktur());
            jtxtTanggalFaktur.setText(dateFormat.format(faktur.getTanggalfaktur()));
            if(faktur.getKodepelanggan()!= null){
                jtxtKodePelanggan.setText(faktur.getKodepelanggan().getKodepelanggan());
                jtxtNamaPelanggan.setText(faktur.getKodepelanggan().getNamapelanggan());
                for(Fakturdetail fd : faktur.getFakturdetailCollection()){
                    tblModel.addRow(new Object[]{
                        fd.getId(),
                        fd.getKodebarang().getKodebarang(),
                        fd.getKodebarang().getNamabarang(),
                        fd.getKodebarang().getHargaStandar(),
                        fd.getQty(),
                        fd.getQty()*fd.getKodebarang().getHargaStandar()
                    });
                }
            }
        }
    }
    private void checkDataFaktur(){
        Faktur fF = fkCtrl.cari(jtxtNomorFaktur.getText());
        boolean cekFaktur = kwCtrl.checkNomorFaktur(fF);
        if(!cekFaktur){
            faktur = fF;
            showDataFaktur();
        }else{
            JOptionPane.showMessageDialog(this, "Faktur dengan Nomor faktur "+fF.getNomorfaktur()+" sudah pernah di proses");
            clearData();
        }
    }
    private void cariDataFaktur(){
        faktur = fkCtrl.cari(jtxtNomorFaktur.getText());
        showDataFaktur();
    }
    private void hitungTotal(){
        Double total = new Double("0");
        try {
        for(int i = 0; i<tblModel.getRowCount();i++){
            total +=(Double) tblModel.getValueAt(i, 5);
        }  
        } catch (Exception e) {
        }
        jtxtGrandTotal.setText(decimalFormat.format(total));
    }
}
