/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.penjualan.desktop.frame;

import aplikasi.penjualan.desktop.InternalFrame.FormKwitansi;
import aplikasi.penjualan.desktop.InternalFrame.FrmBarang;
import aplikasi.penjualan.desktop.InternalFrame.FrmPelanggan;
import aplikasi.penjualan.desktop.InternalFrame.FrmPenjualan;
import aplikasi.penjualan.desktop.util.NavigatorForm;
import java.awt.Desktop;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Null Pointer
 */
public class FrmMain extends javax.swing.JFrame {
    FrmBarang frmBarang;
    FrmPenjualan frmPenjualan;
    FrmPelanggan frmPelanggan;
    FormKwitansi frmKwitansi;
    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        jNew = new javax.swing.JButton();
        jSave = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jPrint = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMaster = new javax.swing.JMenu();
        jBarang = new javax.swing.JMenuItem();
        jPelanggan = new javax.swing.JMenuItem();
        jTransaksi = new javax.swing.JMenu();
        jPenjualan = new javax.swing.JMenuItem();
        jKwitansi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Barang");

        org.jdesktop.layout.GroupLayout jDesktopPane1Layout = new org.jdesktop.layout.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 307, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        jNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/desktop/image/button-add_blue.png"))); // NOI18N
        jNew.setText("New");
        jNew.setFocusable(false);
        jNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewActionPerformed(evt);
            }
        });
        jToolBar1.add(jNew);

        jSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/desktop/image/btn save.png"))); // NOI18N
        jSave.setText("Save");
        jSave.setFocusable(false);
        jSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(jSave);

        jDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/desktop/image/cross.png"))); // NOI18N
        jDelete.setText("Delete");
        jDelete.setFocusable(false);
        jDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        jToolBar1.add(jDelete);

        jPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/desktop/image/btn print.png"))); // NOI18N
        jPrint.setText("Print");
        jPrint.setFocusable(false);
        jPrint.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPrint.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrintActionPerformed(evt);
            }
        });
        jToolBar1.add(jPrint);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasi/penjualan/desktop/image/home.png"))); // NOI18N
        jButton1.setText("Homepage");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jMaster.setText("Master");
        jMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMasterActionPerformed(evt);
            }
        });

        jBarang.setText("Barang");
        jBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarangActionPerformed(evt);
            }
        });
        jMaster.add(jBarang);

        jPelanggan.setText("Pelanggan");
        jPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPelangganActionPerformed(evt);
            }
        });
        jMaster.add(jPelanggan);

        jMenuBar1.add(jMaster);

        jTransaksi.setText("Transaksi");

        jPenjualan.setText("Penjualan");
        jPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPenjualanActionPerformed(evt);
            }
        });
        jTransaksi.add(jPenjualan);

        jKwitansi.setText("Kwitansi");
        jKwitansi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKwitansiActionPerformed(evt);
            }
        });
        jTransaksi.add(jKwitansi);

        jMenuBar1.add(jTransaksi);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .add(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewActionPerformed

navigator = (NavigatorForm) jDesktopPane1.getSelectedFrame();
if(navigator != null){
   navigator.newData(); 
}


// TODO add your handling code here:
    }//GEN-LAST:event_jNewActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
navigator = (NavigatorForm) jDesktopPane1.getSelectedFrame();
if(navigator != null){
navigator.saveData();   
}

        

// TODO add your handling code here:
    }//GEN-LAST:event_jSaveActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        
        navigator = (NavigatorForm) jDesktopPane1.getSelectedFrame();
        if(navigator!= null){
        int jawaban = JOptionPane.showConfirmDialog(null,"Hapus Data ?","Hapus ?",JOptionPane.YES_NO_OPTION);
        if(jawaban== JOptionPane.YES_OPTION){
            
            navigator.deleteData();
        }
        }

    }//GEN-LAST:event_jDeleteActionPerformed

    private void jPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrintActionPerformed
        // TODO add your handling code here:
        
        navigator = (NavigatorForm) jDesktopPane1.getSelectedFrame();
        if(navigator!= null){
           navigator.printData(); 
        }
        
        
        
    }//GEN-LAST:event_jPrintActionPerformed

    private void jBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarangActionPerformed
        // TODO add your handling code here:
        if(frmBarang == null){
            frmBarang = new FrmBarang();
        }
        showForm(frmBarang);
        
        
    }//GEN-LAST:event_jBarangActionPerformed

    private void jMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMasterActionPerformed

    private void jPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPelangganActionPerformed

if(frmPelanggan==null){
    frmPelanggan = new FrmPelanggan();
}
        showForm(frmPelanggan);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jPelangganActionPerformed

    private void jPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPenjualanActionPerformed
        // TODO add your handling code here:
                if(frmPenjualan == null){
            frmPenjualan = new FrmPenjualan();
        }
        showForm(frmPenjualan);
        
    }//GEN-LAST:event_jPenjualanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String uri = "http://www.sopiyan.com";
        if(Desktop.isDesktopSupported()){
            try {
                Desktop.getDesktop().browse(new URI(uri));
            } catch (URISyntaxException ex) {

            } catch (IOException ex) {

            }
        }else{
            Runtime runtime = Runtime.getRuntime();
            try {
                runtime.exec("/usr/bin/firefox -new-window " + uri);
            } catch (IOException ex) {
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jKwitansiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKwitansiActionPerformed
        // TODO add your handling code here:
        if(frmKwitansi == null){
            frmKwitansi = new FormKwitansi();
        }
        showForm(frmKwitansi);
        
    }//GEN-LAST:event_jKwitansiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
   
    NavigatorForm navigator;
    private void showForm(Object obj){
        JInternalFrame jf = null;
        if(obj instanceof JInternalFrame){
            jf = (JInternalFrame) obj;
            if(!jf.isVisible()){
                jDesktopPane1.add(jf);
            }
            jf.setVisible(true);
            try {
                jf.setMaximizable(true);
                jf.setSelected(true);
            } catch (PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jBarang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jDelete;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jKwitansi;
    private javax.swing.JMenu jMaster;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jNew;
    private javax.swing.JMenuItem jPelanggan;
    private javax.swing.JMenuItem jPenjualan;
    private javax.swing.JButton jPrint;
    private javax.swing.JButton jSave;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jTransaksi;
    // End of variables declaration//GEN-END:variables
}
